package com.ashelkov.wallet.bip;

public class Constants {

    private Constants() {}

    // Hardened keys have index >= 0x80000000:
    // https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
    public static final int HARDENED = 0x80000000;

    // All wallets generated by this application are BIP-44 compliant:
    // https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
    public static final int PURPOSE_44 = 44;

    // Bitcoin and Litecoin wallets generated by this application are BIP-84 compliant:
    // https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
    public static final int PURPOSE_84 = 84;

    // Limit on number of addresses to generate for a single coin
    public static final int ADDRESS_LIMIT = 20;

}
